auto: true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

author_sameer: "<a href='http://www.cs.umass.edu/~sameer'>Sameer Singh</a>"
baseurl: "factorie"
factorie_logo: "factorie-logo55.png"
safe: true
lsi: false
pygments: true
